// One-shot extraction script: reads docs/franchise/bestiary.jsx, parses the
// `const D = [...]` array literal, and writes a typed TS module to
// src/shared/franchise/bestiary.ts. The JSX viewer's data is the source of
// truth for the 167 creature shapes; this module is the cross-100g consumer.
//
// Run: pnpm tsx scripts/extract-bestiary.mts
//
// This script is committed for reproducibility / re-extraction; it does not
// run in the build or tests.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");

const jsxPath = resolve(repoRoot, "docs/franchise/bestiary.jsx");
const outPath = resolve(repoRoot, "src/shared/franchise/bestiary.ts");

const src = readFileSync(jsxPath, "utf8");

const startMarker = "const D = [";
const startIdx = src.indexOf(startMarker);
if (startIdx === -1)
  throw new Error("could not find `const D = [` in bestiary.jsx");

let depth = 0;
let endIdx = -1;
for (let i = startIdx + startMarker.length - 1; i < src.length; i++) {
  const ch = src[i];
  if (ch === "[") depth += 1;
  else if (ch === "]") {
    depth -= 1;
    if (depth === 0) {
      endIdx = i + 1;
      break;
    }
  }
}
if (endIdx === -1) throw new Error("could not find matching `]` for D");

const arrayLiteral = src.slice(startIdx + "const D = ".length, endIdx);

const tempUrl = `data:text/javascript,export const D = ${encodeURIComponent(arrayLiteral)};`;
const mod = (await import(tempUrl)) as {
  D: readonly [
    number,
    number,
    readonly (readonly [number, number])[],
    string,
    boolean,
  ][];
};
const D = mod.D;

if (D.length !== 167)
  throw new Error(`expected 167 creatures, got ${D.length.toString()}`);

const tierCounts = new Map<number, number>();
for (const [id, size, cells, name, sym] of D) {
  if (cells.length !== size)
    throw new Error(
      `id ${id.toString()} (${name}) tier ${size.toString()} but ${cells.length.toString()} cells`,
    );
  for (const [r, c] of cells) {
    if (r < 0 || r > 2 || c < 0 || c > 2) {
      throw new Error(
        `id ${id.toString()} (${name}) has cell out of 3x3 grid: [${r.toString()},${c.toString()}]`,
      );
    }
  }
  if (typeof sym !== "boolean")
    throw new Error(`id ${id.toString()} (${name}) has non-boolean sym`);
  tierCounts.set(size, (tierCounts.get(size) ?? 0) + 1);
}

const expectedTierCounts: Record<number, number> = {
  1: 1,
  2: 3,
  3: 12,
  4: 32,
  5: 49,
  6: 42,
  7: 21,
  8: 6,
  9: 1,
};
for (const [tier, count] of Object.entries(expectedTierCounts)) {
  const actual = tierCounts.get(Number(tier)) ?? 0;
  if (actual !== count)
    throw new Error(
      `tier ${tier}: expected ${count.toString()}, got ${actual.toString()}`,
    );
}

const seen = new Set<number>();
for (const [id] of D) {
  if (seen.has(id)) throw new Error(`duplicate id: ${id.toString()}`);
  seen.add(id);
}

const formatCells = (cells: readonly (readonly [number, number])[]): string =>
  "[" +
  cells.map(([r, c]) => `[${r.toString()}, ${c.toString()}]`).join(", ") +
  "]";

const lines: string[] = [];
lines.push(
  "// AUTO-GENERATED by scripts/extract-bestiary.mts from docs/franchise/bestiary.jsx.",
);
lines.push(
  "// Do not edit by hand. Re-run the script if the bestiary changes.",
);
lines.push("");
lines.push('import type { CreatureShape } from "./types.ts";');
lines.push("");
lines.push("export const BESTIARY: readonly CreatureShape[] = [");
for (const [id, size, cells, name, sym] of D) {
  const tier = size as 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
  lines.push(
    `  { id: ${id.toString()}, tier: ${tier.toString()}, cells: ${formatCells(cells)}, nameDe: ${JSON.stringify(name)}, mirrorSymmetric: ${sym.toString()} },`,
  );
}
lines.push("];");
lines.push("");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join("\n"), "utf8");

console.log(
  `wrote ${outPath} (${D.length.toString()} creatures, tiers ${[
    ...tierCounts.entries(),
  ]
    .sort(([a], [b]) => a - b)
    .map(([t, c]) => `${t.toString()}:${c.toString()}`)
    .join(" ")})`,
);

void pathToFileURL;
